name: Sync Upstream
on:
  schedule:
    - cron: '0 0/8 * * *'  # 每周运行一次
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Configure git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Add upstream
      run: |
        git remote add upstream https://github.com/coolsnowwolf/lede.git
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout master
        git merge upstream/master
        if [ $? -ne 0 ]; then
          echo "Merge conflict detected, attempting to resolve..."
          git merge --abort
          git checkout -b temp-branch
          git pull upstream master --rebase
          git checkout master
          git merge temp-branch
          git branch -d temp-branch
        fi

    - name: Push changes
      run: |
        git push origin master
